package com.chainreaction.realtime.api;

public enum RealtimeEventType {
    PLAYER_JOINED,
    PLAYER_LEFT,
    PLAYER_KICKED,
    ROOM_CLOSED,
    GAME_STARTED,
    TURN_STARTED,
    WORD_SUBMITTED,
    AI_GENERATION_STARTED,
    STORY_SEGMENT_ADDED,
    TURN_SKIPPED,
    VOTING_STARTED,
    VOTE_RESULTS_UPDATED,
    GAME_FINISHED,
    ERROR_EVENT
}
