package com.chainreaction.common.error;

public enum ErrorCode {
    AUTH_REQUIRED,
    ACCESS_DENIED,
    ACCOUNT_SUSPENDED,
    ACCOUNT_DELETED,
    DUPLICATE_EMAIL,
    INVALID_CREDENTIALS,
    INVALID_REFRESH_TOKEN,
    INVALID_PASSWORD_RESET_TOKEN,
    VALIDATION_FAILED,
    INTERNAL_ERROR
}
